name: Process mail
on:
  push:
  schedule:
    - cron: '9 */3 * * *' # every 3rd hour, at minute 9
jobs:
  process_mail:
    environment: production
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - run: npm ci
      - run: npm run build
      - run: npm run mail
        env:
          AUTHORIZATION: ${{ secrets.AUTHORIZATION }}
